site_name: krnel-mrkov

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.top # Añade botón para volver arriba (útil en documentación larga)

extra:
  alternate:
    - name: Español
      link: /es/
      lang: es
    - name: English
      link: /en/ 
      lang: en